# Generated by Django 5.0 on 2024-11-23 19:17

import Apps.Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=Apps.Accounts.models.user_directory_image_path),
        ),
    ]
